# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b373195c75d41125a1acd95c6743bc9ff0ad0dbae9a5ce65b327d4fa9ae31d15e092c45d1a402cb3519fd9a501aee7c00f3a2da0cd3ff43c832e9e2349808db

test:
  secret_key_base: 9b71ff033daa96eab7615b76ee8936ee4d5b6262968918750ae2b2963e261fd5f4eaf85fc26c6c28231c99f14ce0fc1aadf5d176484b211445fe15e0b3ae15d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
